spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/testDB
    username: root
    password: hwryu990927!
    hikari:
      maximum-pool-size: 40

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
